import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        secondary: "#545b6d",
        "primary-fixed-dim": "#5dea5a",
        "on-tertiary-fixed-variant": "#005e65",
        "on-error": "#ffefec",
        "inverse-surface": "#070e1d",
        "on-surface-variant": "#545b6d",
        "on-background": "#282f3f",
        "on-secondary-fixed": "#373d4e",
        primary: "#006b11",
        "on-primary-fixed-variant": "#006710",
        "surface-bright": "#f5f6ff",
        "on-tertiary-fixed": "#003f44",
        "inverse-primary": "#6cf967",
        "on-tertiary-container": "#00535a",
        "on-tertiary": "#d2faff",
        "on-secondary-container": "#495061",
        "on-primary": "#d2ffc5",
        "on-secondary-fixed-variant": "#535a6b",
        "secondary-dim": "#494f61",
        "surface-dim": "#c9d4f2",
        background: "#f5f6ff",
        "on-secondary": "#f0f2ff",
        "surface-container-low": "#edf0ff",
        "surface-container-highest": "#d3dcf9",
        "surface-container-high": "#d9e2fd",
        tertiary: "#00666e",
        "tertiary-fixed": "#1aedff",
        "surface-tint": "#006b11",
        "tertiary-fixed-dim": "#00deef",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d3dcf9",
        "primary-container": "#6cf967",
        "error-container": "#f95630",
        surface: "#f5f6ff",
        "secondary-container": "#d9dff5",
        "tertiary-container": "#1aedff",
        "surface-container": "#e1e8ff",
        "primary-fixed": "#6cf967",
        error: "#b02500",
        "secondary-fixed-dim": "#cbd1e6",
        "on-primary-container": "#005c0d",
        "outline-variant": "#a6adc1",
        "inverse-on-surface": "#969db0",
        "error-dim": "#b92902",
        "secondary-fixed": "#d9dff5",
        "tertiary-dim": "#005960",
        "on-surface": "#282f3f",
        "on-primary-fixed": "#004708",
        "on-error-container": "#520c00",
        "primary-dim": "#005d0e",
        outline: "#707789",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },

      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};

export default config;
