import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "../components/ui/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastProvider />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
